### ISSUE TITLE
<asset> tags are missing in 3ds Max exporter

### ISSUE THREAD

**Issue by glaforte** [KhronosGroup/OpenCOLLADA#401] opened 2016-02-17 20:30 UTC
Hello Remi!

We're using the OpenCOLLADA 3ds Max exporter here at CM Labs.
Our clients are telling us that all their meshes are rotated 90 degrees, so I had a look.
They had downloaded the latest version from the pull request 2016-02-13_11-13-25_#200.
So, we told them quickly to use only official versions, instead...

I did have a look with a compare tool and I wanted to report that the "asset" tags are missing!

Regards,
Guillaume Laforte
Now @ CM Labs

**Comment by RemiArnaud** [comment] 2016-02-18 03:48
¡Ay, caramba!

 Sorry about this Guillaume. As you can see we've put a lot of effort in contributing and maintaining openCOLLADA, but we are focused more on Maya plug-in as you can see. 

 We compile and at least make sure the build is not broken for various versions of Max, but we don't have internal users or developers. So thanks for reporting the issue

 Any chance you would have someone to have a quick look at what the problem is and submit a pull request? There was no many changes to the max plugin in a while, so hopefully it would be easy to spot. 

 Going forward, would there be interest in helping us with testing the max plug-in?  
 I'd like to do a major release soonish, because it's been a long while we have done one, and there was some good bug fixes and improvements. Would be nice to validate both max and Maya plugin for a major release soon?

**Comment by glaforte** [comment] 2016-02-20 01:28
Hello Remi,

I created a pull request for the <asset> tag fix. And it looks like you've got the repository set-up to automatically merge... So, errr, I will close the issue.

I'll ask our Creative Product Specialist to do more tests, on Monday morning, with some of the 3D models.

About providing testing, I'll be happy to report anymore issues found at CM Labs with our content pipeline. I can provide some fixes as well - I opened your code-base for the first time, just now, and it looks well organized. Unfortunately, CM Labs is not a very representative test-bed: we use the OpenCOLLADA exporter only and we only export a small subset: the profile_common material, simple geometries and the visual scene graph.

Regards,
Guillaume

**Comment by RemiArnaud** [comment] 2016-02-20 02:59
Hi Guillaume,
 This is fantastic. 
 The PR does not automatically merge, we have a robot that want to build it, but he is a bit too verbose because he ask permission for each target :-)

**Comment by RemiArnaud** [comment] 2016-02-20 03:03
I gave the robot authorization for the build, but the build server is off this week end, we're updating the hardware over the week end. We do that rarely and it happe to be this week end, lucky you. So early next week we'll have the status of all the builds, as well as the artifacts of the build ready for testing if the build is successful. 

Thanks a bunch for your help!

**Comment by RemiArnaud** [comment] 2016-02-20 19:19
PR is https://github.com/KhronosGroup/OpenCOLLADA/pull/406

**Comment by RemiArnaud** [comment] 2016-03-04 01:41
it was confirmed that https://github.com/KhronosGroup/OpenCOLLADA/pull/408 did fix the bug
I will close #406 now, and will close this issue as soon as 408 is merged

**Closed** 2016-03-04 05:59 UTC
