### ISSUE TITLE
Loading failure - 3dsMax 2014

### ISSUE THREAD

**Issue by corentinjaffre** [KhronosGroup/OpenCOLLADA#417] opened 2016-04-12 07:58 UTC
I can't load the plug-in colladaMaxNew. I tried several versions, but each time I have:
**"failed to initialize. 
Error code 127 - The specified procedure could not be found."**

My 3dsmax:
3dsmax 2014 : version 16.0 SP5 commercial

The last plug-in version I tried:
2016-04-11_11-53-38_#119 x64, release max2014

Corentin

**Comment by RemiArnaud** [comment] 2016-04-12 15:32
I wonder since when this problem exists. Could you try to find out using a very old version and then splitting in half until you find the first version that breaks? 
Or maybe the oldest version in opencollada.fl4re.com is already broken?

**Comment by corentinjaffre** [comment] 2016-04-12 15:49
On 12/04/2016 17:32, Rémi Arnaud wrote:
>
> I wonder since when this problem exists. Could you try to find out 
> using a very old version and then splitting in half until you find the 
> first version that breaks?
> Or maybe the oldest version in opencollada.fl4re.com is already broken?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/KhronosGroup/OpenCOLLADA/issues/417#issuecomment-208963514>
>


I tried the first one (2015-05-16_00-23-11_#61) and the last one 
(2016-04-11_11-53-38_#119).
The only colladaMax which works OK with my 3dsmax2014 is the last one 
fron the official github page :
1.4.1, from 2013-05-08

It's working well, but there are still bugs in this version, like 
specular values exported as shininess.

If you have older colladaMaxNew versions than the ones in 
opencollada.fl4re.com, I'll be okay to test them if you need.

Corentin

**Comment by RemiArnaud** [comment] 2016-04-13 00:59
Hi Corentin,

 I just tested with the latest MAX plugin for 2014, I added the 3rd party path, and launched 3dsmax, and it worked like a charm.
I was able to load and use the plugin

**Comment by RemiArnaud** [comment] 2016-04-13 01:04
Note that we only build 2014 for 64bits. Please make sure you are using 2014 64bits

**Comment by RemiArnaud** [comment] 2016-04-13 01:08
another thing I'm thinking about is the collada plug in is linked with morpher_2014  and I have morpher.dlm plugin loaded in max

**Comment by corentinjaffre** [comment] 2016-04-13 07:47
Thanks for your answers Remi!
. 2014 32 bits doesn't exist anymore, so I'm using 2014 64bits
. morpher.dlm is loaded in max
.  "I added the 3rd party path" I just copied the .dle in plug-ins. Do I need to do something else ?
Is there somewhere a .log or something which could help me tell you what's wrong ?

**Comment by RemiArnaud** [comment] 2016-04-13 18:31
that's outside my knowledge of Max I'm afraid. I agree that we need more log / debug information.

@glaforte @Birdy3D  any idea what we can do to help Corentin ?

**Comment by RemiArnaud** [comment] 2016-04-14 22:34
maybe the visual studio redistributable are needed. They should be installed when you install max though

https://www.microsoft.com/en-us/download/details.aspx?id=13523

**Comment by glaforte** [comment] 2016-04-15 13:59
The simplest way to identify the issue is using the Dependency-Walker: http://www.dependencywalker.com/

This is an old tool from Microsoft that is great at identifying missing DLL dependencies.
1. Download it, start depends.exe
2. File -> Open. Find and open the COLLADAMaxNew.dle file.
---> At this point, Depends will complain about a lot of standard 3ds Max DLLs as missing.
3. Go in the Options -> Configure Module Search Order.
4. Click "Browse...", Find your 3dsMax root installation folder.
----> For my machine, this is : C:\Program Files\Autodesk\3ds Max 2016\
5. Click "Add Directory".
6. Click "Browse...", Find your 3dsMax standard plug-in installation folder.
----> For my machine, this is : C:\Program Files\Autodesk\3ds Max 2016\stdplugs\
7. Click "Add Directory". Click "Ok".
8. Depends will have a new pop-up: "Would you like to refresh ....". Answer "Yes".
9. In the DLL Tree: collapse all the sub-folders, keeping only the first level of DLLs.
----> Are there any yellow question marks or red box in the tree?

**Comment by corentinjaffre** [comment] 2016-04-15 14:18
Thanks for all your answers and feedback, it's really appreciated :)

I did the test, and yes, the morpher.dlm is marked in red.
I also checked, and my 3dsmax 2014 sp5 has the morpher.dlm in stdplugs, and it's loaded when I start 3dsmax.

**Comment by glaforte** [comment] 2016-04-15 19:16
When a DLL is marked in red in Dependency-Walker, it means that it finds the DLL, but some of the symbols that the DLE expects in the DLL are not found (and cannot be imported, so the DLL load will fail).

What are the symbols missing?

**Comment by corentinjaffre** [comment] 2016-04-15 20:05
?buildFromNode@morphChannel@@QEAAXPEAVINode@@HHH@Z
is red.

**Comment by RemiArnaud** [comment] 2016-04-15 21:53
Ah!  Same issue there: https://github.com/KhronosGroup/OpenCOLLADA/issues/404

What about the static linked collada plugin? Does this one work?

**Comment by corentinjaffre** [comment] 2016-04-16 17:26
Same problem with the static linked collada plugin.

**Comment by glaforte** [comment] 2016-04-18 12:15
The morphChannel::buildFromNode function is provided in the 3dsMax samples.
It might be simplest to copy it over to the DAE plug-in.

On the other hand, considering that this symbol is explicitly exported, we cannot assume Autodesk was successful at exporting other symbols in the Morpher plug-in. So, you'd need someone who can reproduce the issue to appropriate the Autodesk code to fix the issue....

**Comment by fabrobinet** [comment] 2016-04-23 15:06
@RemiArnaud @corentinjaffre I think I remember about this issue... 
If you look at this page: https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools you'll see that I had disabled the morphing, because of this I am pretty sure. That was the plan to put it back but in the meantime it was better to disable morphing than not being able to load the plug-in :)

@RemiArnaud please, could you comment out all references to the problematic method and recompile for Corentin ? I am sorry I can't otherwise I wouldn't bother you :).  
Many thanks.

**Comment by RemiArnaud** [comment] 2016-04-23 17:55
You can submit a PR and the robot will build for you

**Comment by jerome-jacob** [comment] 2016-05-23 09:43
buildFromNode function signature has changed with one of Max 2014 service packs. But the Max SDK has not been updated accordingly. So we can't fix this issue unless Autodesk provides us an updated max SDK. We'll disable morph support for 2014 for the moment.

**Comment by RemiArnaud** [comment] 2016-05-23 23:59
@jerome-jacob could you create a PR that remove morph export completely from exporter, if max_version >= 2014. Also updating documentation for max exporter to explain what's going on re: morphing export. 

BTW could you rename https://github.com/KhronosGroup/OpenCOLLADA/blob/master/COLLADAMax/README into README.txt please.

**Comment by RemiArnaud** [comment] 2016-06-11 06:59
@corentinjaffre could you please try the 3dsmax 2014 SP5 release build you will find in https://github.com/KhronosGroup/OpenCOLLADA/pull/444 ?

**Comment by RemiArnaud** [comment] 2016-06-11 07:09
@corentinjaffre  sorry, spoke too fast. I started build again, let see if it compiles this time

**Comment by RemiArnaud** [comment] 2016-06-22 22:32
This is merged - see the MAX 2014 SP5 build from release 1.6.19 and above

**Closed** 2016-06-22 22:32 UTC
Labels: bug
