### ISSUE TITLE
Bones/weights not exporting correctly

### ISSUE THREAD

**Issue by AlunAlun** [KhronosGroup/OpenCOLLADA#441] opened 2016-06-03 09:52 UTC
In the scene below, the weights and indices are not correct when exported using OpenCollada for Maya. There are 6 bones, it references 6 joints, but the DAE only points to one - the vertex_weights only have 0 as the bone index.

If you export the scene with OpenCollada Maya, and then reimport to Maya with the OpenCollada importer, you'll see the exact same error that I get in the importer in my engine.

[dodgy_tongue.ma.zip](https://github.com/KhronosGroup/OpenCOLLADA/files/297342/dodgy_tongue.ma.zip)

**Comment by RemiArnaud** [comment] 2016-06-07 07:22
the maya file has only a single active bone when loaded in maya2015, so the problem is with the maya file, not with the exporter.
I recommend you update your maya sofware.

closing bug

**Closed by RemiArnaud** 2016-06-07 07:22 UTC
