### ISSUE TITLE
3dsMax exporter:  'hidden' node because of changed pivot unaffected by "Bake Matrices"

### ISSUE THREAD

**Issue by Herst** [KhronosGroup/OpenCOLLADA#269] opened 2014-08-02 12:45 UTC
Maybe I misunderstood the "Bake Matrices" option but I would've expected that it would also apply to when I change the pivot point (without using the "Reset XForm" tool afterwards) because that way 3ds Max creates a node whose presence isn't apparent from the UI.

Even worse yet, this node has no name and so if the unique name machinery kicks in you get nodes with names such as "Object_2345_" which causes confusion.

**Comment by RemiArnaud** [comment] 2016-03-03 04:08
any body with 3ds max expertise want to chime in ?

**Comment by RemiArnaud** [comment] 2016-03-04 01:40
I was told that in order to be exported correctly, 3dsMax user has to do a reset Xform and collapse before the export.

Does this make sense and solve your problem?

**Comment by Herst** [comment] 2016-03-04 12:01
I mentioned already in the original post that "Reset XForm" is a possible workaround but I see no reason whatsoever why this should be an expected behavior (or put differently: there is no benefit ever in not using the workaround) so I still consider this a bug in the exporter.

**Comment by RemiArnaud** [comment] 2016-03-05 01:01
this should be documented, it is the expected behavior of this plugin. 
it could be improved, and we are open to pull requests.

**Comment by Brakebein** [comment] 2016-03-08 12:08
I recently started to use OpenCOLLADA and now I'm facing the same issue having an additional node when pivot point was changed. And on reimporting the DAE file in 3ds max, it will create a dummy object as parent node to the actual mesh object (I only did the import to test the behaviour).
```xml
<node id="node-dach_fluegel_001" name="dach_fluegel_001">
    <matrix>1 0 0 46752 0 1 0 -122079.3 0 0 1 23732.88 0 0 0 1</matrix>
        <node>
            <matrix>1 0 0 0 0 1 0 0 0 0 1 2280.227 0 0 0 1</matrix>
            <instance_geometry url="#geom-dach_fluegel_001">
            ...
```
Applying "Reset XForm" is a workaround, but sometimes you want the modifier stack to be preserved. 
If I'm not wrong, the transformation of the pivot point (lower matrix) just needs to be applied to the object matrix (upper matrix) and the 'blind' node can be deleted. I think, I will post-process the DAE file until this behaviour has been improved.

**Comment by RemiArnaud** [comment] 2016-04-22 00:15
I am wondering what happen if you remove the <node> that has no 'id' ? this is an intermediate node, that is not referenced.
<matrix> can follow a <matrix>, it just means they need to be applied in that order. Without the <node> they most likely get multiplied at load time when importing in Max ?

**Comment by RemiArnaud** [comment] 2016-06-24 18:55
I am closing this because as far as I can see there is no bug.
The COLLADA document exported is correct in all cases, the position of the instanced geometry is given by the transformation hierarchy, and is correctly provided and exported.
The user can use Max 'Reset Xform' to simplify the hierarchy if for some reason the user want to do so, otherwise the COLLADA loaded should have no problem to correctly load the exported document.

**Closed by RemiArnaud** 2016-06-24 18:55 UTC
Labels: wontfix

**Comment by Herst** [comment] 2016-06-24 21:56
In my case it didn't load correctly because there was a node (with an id) I wasn't expecting when I was looking for objects by id. At least an export warning would be have been nice.
