### ISSUE TITLE
specs: SID Addressing clarification

### ISSUE THREAD

**Issue by recp** [KhronosGroup/OpenCOLLADA#507] opened 2017-04-08 14:10 UTC
Hello,

I'm working on COLLADA and now trying to load textures,
I'm confused about SID addressing used in sample dae files (duck.dae)

Here COMMON profile:
```COLLADA
           <profile_COMMON>
                <newparam sid="file2-surface">
                    <surface type="2D">
                        <init_from>file2</init_from>
                        <format>A8R8G8B8</format>
                    </surface>
                </newparam>
                <newparam sid="file2-sampler">
                    <sampler2D>
                        <source>file2-surface</source>
                        <minfilter>LINEAR_MIPMAP_LINEAR</minfilter>
                        <magfilter>LINEAR</magfilter>
                    </sampler2D>
                </newparam>
                <technique sid="common">
                    <blinn>
                        <diffuse>
                            <texture texture="file2-sampler" texcoord="TEX0"/>
                        </diffuse>
```
How does this work? **file2-sampler** is SID of newparam and it referenced in diffuse material. Specs (1.4, 1.5) says (SID Addressing Syntax):
> The first part is the id attribute of an element in the instance document or a dot segment ( “.” ) indicating that this is a relative address.

But there is no id prefix like "id1/file2-sampler"? I hope we are not enforced to find a valid **file2-sampler** in &lt;texture/&gt; scope ?

Related: https://www.khronos.org/bugzilla/show_bug.cgi?id=1924

Thanks for clarification

**Comment by recp** [comment] 2017-04-17 14:45
I guess, I should look up texture sampler (in this case "file2-sampler") from active profile (profile_COMMON or other) :

**[Active Profile]**/file2-sampler, as default: **profile_COMMON**/file2-sampler

instead of 

 **[id or relative path]**/file2-sampler

**Comment by RemiArnaud** [comment] 2017-04-17 16:59
The way I think about it is that there is a SID='file2-sampler' in the scope of the <technique> so there is no ambiguity.
The 'id/' is needed in addressing elements that have there SID defined elsewhere.

**Comment by mbarnes-sb** [comment] 2017-04-17 20:55
Yes it's a schema bug in 1.4 that was fixed in 1.5 (texturing was redesigned). The workaround has been to search in the implied parent scope (i.e `<effect id="parent"`> element), e.g. construct an sidref value of "`./`file2-sampler" and process normally.

**Comment by recp** [comment] 2017-04-17 21:34
@RemiArnaud  @mbarnes-sb thanks for clarification,

I didn't know that any parent sid could be targeted without id, I thought that with `id` any specified element can be targeted or with dot `./` any sub element of this  element can be targeted like UNIX path ./ ../ 

I were finding sid elements by breadth-first search (from top to bottom elements)

to find a valid sid-ed element in current scope (without id) I need to traverse from current element to top elements, this seems very basic way, I'll try to improve this (caching, algorithms...) if I can

**Comment by mbarnes-sb** [comment] 2017-04-17 21:51
The parent scope of `"./"` is defined by the first parent element with id attribute value present. In this case it should always be the `<effect>` element (you can add a semantic check and warning if the derived scope resolves to something else) parenting the `<profile_COMMON>` element.

**Comment by recp** [comment] 2017-04-17 22:20
> The parent scope of "./" is defined by the first parent element with id attribute value present. In this case it should always be the <effect> element (you can add a semantic check and warning if the derived scope resolves to something else) parenting the <profile_COMMON> element.

@mbarnes-sb great explanation!

So I didn't need to traverse to parents for sid, I just need pick right parent of `./` which is `first parent element with id attribute value present` then apply breadth-first search

I've checked spec now, the `id` attribute of effect is required :) I can add a flag to memory node about this need to `id` attribute or not so if there is no `id` attrib specified then it will not continue to parents as expected

In this case `./` will cause to select `<effect>` element to resolve sid, then select profile (profile_COMMON or which one is selected) then search sid-ed element by breadth-first search, 

last thing; selecting profile (default is profile_COMMON) is required after found first id-ed parent element of `./`, right? if found parent is `<effect>` of course

**Comment by recp** [comment] 2017-04-17 22:52
One last thing `<technique>` element can have id attribute so if `<technique id="...">` is present then resolver will try to find `file2-sampler` in technique(fx) element, so it will fail because newparam is only valid in effect and profile elements?

**Comment by mbarnes-sb** [comment] 2017-04-17 23:17
That's why I suggest a semantic check. Issue a diagnostic warning then search again for the grandparent `effect` in that case. Because of the schema bug, that's the only meaningful resolution of the synthetic sidref and this approach leverages existing sidref resolver functions (in your code) vs a special case hack. I.e. this is how it was supposed to work.

**Comment by recp** [comment] 2017-04-18 06:43
Thank you very much for clarifying/confirming the schema bug and how to handle it

**Comment by mick-p1982** [comment] 2017-04-18 16:50
Recp asked me to look at this discussion. It seems very active. (I'm glad to see mbarnes taking an interest in COLLADA.)

I just want to add that I'm working on a serious reference implementation of COLLADA and that the Addressing section of the specification is highly misleading and problematic. There is only one case where the SIDREF addressing mode is used. That's <animation><channel target>. That's the only place you get any mileage out of that addressing mode. And it has many holes.

Where SIDs work best is in the <effect> specification. It is organized like a programming language where variables have nested scope and the SIDs are searched for backward through block-scope rules. This is what you're dealing with right now Recp. (It's not a bug. The animation targeting algorithm is for top-down cross-referencing, whereas effects are bottom up emulating shader programming.)

Unfortunately there is a different addressing model for almost every nontrivial occasion where an attribute is used to connect an element to another element. There is a great variety and its worse when the differences are only subtle. I honestly believe throughout the entire specification there are about 20 implied addressing models. They are all highly constrained by the realities of what they must accomplish.

I don't think it had to be this way. I think the design is haphazard ("schizophrenic") and it makes the existing COLLADA standards indefensible. So I think they should be considered experimental standards. Unsuitable fore real world applications... But not hopeless because all ambitious technology has to begin somewhere. I just worry that Khronos has lost interest in COLLADA. I'm surprised to see Remi sticking with it after so long...

This is the real problem at the root of COLLADA. It shouldn't require several different algorithms to sanely link things up. Only a superhuman patience would put up with it. And it makes COLLADA deadly to development times. COLLADA has to be algorithm friendly because there's no one-way to work with COLLADA data. There's as many ways as there are applications.

**Closed** 2017-04-21 07:10 UTC
