### ISSUE TITLE
Maya 2015 x64 - Animations not Exported when Bake Transforms Turned On

### ISSUE THREAD

**Issue by CWolfs** [KhronosGroup/OpenCOLLADA#319] opened 2015-05-22 10:48 UTC
When exporting a model with animations with animations turned on and bake transforms turned on, the <library_animations> node is not exported at all. When I turn back transforms off, the node is exported.

I'm using Maya 2015  x64 OpenCOLLADA plugin.

Is this a bug or intended functionality? Seems like a bug to me. I can provide the model I am using if you want.

EDIT: Here is a screenshot of my export settings https://dl.dropboxusercontent.com/u/3983502/ColladaSettings.png

**Comment by RemiArnaud** [comment] 2015-05-22 16:23
which build are you using?

current windows build is #51

see opencollada.fl4re.com -> COLLADAMaya -> win -> 2015-05-21_11-19-26_#51

**Comment by CWolfs** [comment] 2015-05-22 17:20
I thought I was using the latest, but seems I'm using build #40 from the folder '2015-05-06_18-47-38_#40'

**Comment by RemiArnaud** [comment] 2015-05-22 18:21
could you test with # 51+ ? 
there was some updates in animations since # 41

**Comment by mycheckgithub** [comment] 2015-05-22 23:17
If you still have the bug with #51+, Could you please provide me your .mb ?
I tested and didn't found any issue with node not exported when exporting animation with baked option turned on.

**Comment by RemiArnaud** [comment] 2015-08-04 17:06
closing as this can't be reproduced. Please re-open if issue re-appear in recent builds

**Closed by RemiArnaud** 2015-08-04 17:06 UTC
